In [2]:
import math
import os
import scipy
from scipy.optimize import lsq_linear
import numpy as np
from scipy.linalg import toeplitz
import matplotlib.pyplot as plt
from scipy.stats import multivariate_normal, halfnorm
import random
from scipy.io import loadmat
import random
import pickle
import sys
sys.path.append(r"c:\Users\katie\OneDrive\Documents\GitHub\trial")
import PCA_Regress as pcar

PCA_Regress.py loaded


In [3]:
base_path =r"c:\Users\katie\OneDrive\Desktop\Thesis"
with open(base_path+'\J_neu.pkl', "rb") as input_file:
    J_pickle = pickle.load(input_file)
del input_file



base_path =r"c:\Users\katie\OneDrive\Desktop\Thesis"
with open(base_path+'\J_mus.pkl', "rb") as input_file:
    J_pickle_m = pickle.load(input_file)
del input_file

# base_path = "/Users/kb6113/Desktop/Thesis"
# with open(base_path+'/J_neu.pkl', "rb") as input_file:
#     J_pickle = pickle.load(input_file)
# del input_file

# with open(base_path+'/J_mus.pkl', "rb") as input_file:
#     J_pickle_m = pickle.load(input_file)
# del input_file

J_all_tensor = J_pickle['J_all']['interpPSTH']
J_all_PSTH = pcar.shape_matrix(J_all_tensor)
J_all_PSTH_scaled = pcar.scaling(J_all_tensor)

J_mus_tensor = J_pickle_m['interpPSTH']
J_mus_PSTH = pcar.shape_matrix(J_mus_tensor)
J_mus_PSTH_scaled = pcar.scaling(J_mus_tensor)
J_mus_stack = np.vstack((J_mus_tensor, J_mus_tensor, J_mus_tensor, J_mus_tensor))
print(J_mus_stack.shape)
print(J_all_tensor.shape)

_, sing, _ = pcar.run_PCA(J_all_PSTH_scaled, 6)
print(sing.shape)


<>:2: SyntaxWarning: invalid escape sequence '\J'
<>:9: SyntaxWarning: invalid escape sequence '\J'
<>:2: SyntaxWarning: invalid escape sequence '\J'
<>:9: SyntaxWarning: invalid escape sequence '\J'
C:\Users\katie\AppData\Local\Temp\ipykernel_29820\2578773143.py:2: SyntaxWarning: invalid escape sequence '\J'
  with open(base_path+'\J_neu.pkl', "rb") as input_file:
C:\Users\katie\AppData\Local\Temp\ipykernel_29820\2578773143.py:9: SyntaxWarning: invalid escape sequence '\J'
  with open(base_path+'\J_mus.pkl', "rb") as input_file:


(108, 32, 236)
(108, 202, 236)
(202, 6)


In [4]:
# J_mus_stack = np.vstack((J_mus_PSTH, J_mus_PSTH, J_mus_PSTH, J_mus_PSTH))
# J_mus_mc = J_mus_stack - np.mean(J_mus_stack, axis = 0)
# J_all_mc = J_all_PSTH - np.mean(J_all_PSTH, axis = 0)


W, N, proj = pcar.fig_4(J_all_tensor, J_mus_stack)




made it to r_regress
(7128, 6)
(7128, 3)
regress
regress
regress
regress
regress
regress
regress
regress
regress
regress
regress
regress
regress
regress
regress
regress
regress
regress
regress
regress
>>> best_lam returning: 0.01


In [6]:
print(W)
print(proj)


[[10577808.96410785   133334.969463   -1888499.01678292]
 [-5431179.95313359  2384121.96802877  -352456.57702922]
 [-1377065.60118844  -383790.28611823   -78162.24476164]
 [   31740.26656075   239691.73044563   233540.68138474]
 [  301346.73396213   120823.85374182    53880.96475391]
 [  -23245.57842092  -103306.50295773   -35888.27815229]]
[[ 2466513.33618854  2090387.05904034  -447753.53534803 ...
   1430247.24251234   275725.91263814 -1675281.42071537]
 [ 2490712.18085721  2103765.93604783  -413796.26868049 ...
   1442635.96936251   280085.63215647 -1719503.65084987]
 [ 2523149.20788298  2124858.42579797  -387828.39027029 ...
   1460453.48435766   285516.02218481 -1766177.48657119]
 ...
 [-2216030.74832564 -1846041.31540009  -153025.13207654 ...
  -1205310.92735274  -207341.89153583  1673840.92107383]
 [-2301564.59979725 -1919369.58859842   -91737.57363965 ...
  -1262892.72866748  -221862.17150597  1723957.79540989]
 [-2371373.04841899 -1979278.95192116   -38434.04475262 ...
  -1310