In [1]:
import math
import os
import scipy
from scipy.optimize import lsq_linear
import numpy as np
from scipy.linalg import toeplitz
import matplotlib.pyplot as plt
from scipy.stats import multivariate_normal, halfnorm
import random
from scipy.io import loadmat
import random
import pickle
import sys
sys.path.append(r"c:\Users\katie\OneDrive\Documents\GitHub\trial")
import PCA_Regress as pcar

In [2]:
base_path =r"c:\Users\katie\OneDrive\Desktop\Thesis"
with open(base_path+'\J_neu.pkl', "rb") as input_file:
    J_pickle = pickle.load(input_file)
del input_file



base_path =r"c:\Users\katie\OneDrive\Desktop\Thesis"
with open(base_path+'\J_mus.pkl', "rb") as input_file:
    J_pickle_m = pickle.load(input_file)
del input_file

# base_path = "/Users/kb6113/Desktop/Thesis"
# with open(base_path+'/J_neu.pkl', "rb") as input_file:
#     J_pickle = pickle.load(input_file)
# del input_file

# with open(base_path+'/J_mus.pkl', "rb") as input_file:
#     J_pickle_m = pickle.load(input_file)
# del input_file

J_all_tensor = J_pickle['J_all']['interpPSTH']
J_all_PSTH = pcar.shape_matrix(J_all_tensor)
J_all_PSTH_scaled = pcar.scaling(J_all_tensor)

J_mus_tensor = J_pickle_m['interpPSTH']
J_mus_PSTH = pcar.shape_matrix(J_mus_tensor)
J_mus_PSTH_scaled = pcar.scaling(J_mus_tensor)
J_mus_stack = np.vstack((J_mus_tensor, J_mus_tensor, J_mus_tensor, J_mus_tensor))
print(J_mus_stack.shape)
print(J_all_tensor.shape)

_, sing, _ = pcar.run_PCA(J_all_PSTH_scaled, 6)
print(sing.shape)


<>:2: SyntaxWarning: invalid escape sequence '\J'
<>:9: SyntaxWarning: invalid escape sequence '\J'
<>:2: SyntaxWarning: invalid escape sequence '\J'
<>:9: SyntaxWarning: invalid escape sequence '\J'
C:\Users\katie\AppData\Local\Temp\ipykernel_23728\2578773143.py:2: SyntaxWarning: invalid escape sequence '\J'
  with open(base_path+'\J_neu.pkl', "rb") as input_file:
C:\Users\katie\AppData\Local\Temp\ipykernel_23728\2578773143.py:9: SyntaxWarning: invalid escape sequence '\J'
  with open(base_path+'\J_mus.pkl', "rb") as input_file:


(108, 32, 236)
(108, 202, 236)
(202, 6)


In [3]:
# J_mus_stack = np.vstack((J_mus_PSTH, J_mus_PSTH, J_mus_PSTH, J_mus_PSTH))
# J_mus_mc = J_mus_stack - np.mean(J_mus_stack, axis = 0)
# J_all_mc = J_all_PSTH - np.mean(J_all_PSTH, axis = 0)


N_tilde, M_tilde, N_tilde_reg = pcar.fig_4(J_all_tensor, J_mus_stack)




regress
regress
regress
regress
regress
regress
regress
regress
regress
regress
regress
regress
regress
regress
regress
regress
regress
regress
regress
regress
>>> best_lam returning: 0.01


In [5]:

print(N_tilde)


[[ 0.08470738 -0.01312989 -0.01915041]
 [-0.40170417 -0.03058783  0.07507056]
 [-0.45461012  0.19878206 -0.01555808]
 [ 0.18069567  0.12394895 -0.02845292]
 [-0.10847038 -0.12590694 -0.07713299]
 [ 0.20882292  0.1460958  -0.06545721]]
